# Generated by Django 5.1.6 on 2025-03-23 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_notice_created_by_remove_notice_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='event',
            name='updated_at',
        ),
    ]
