# Generated by Django 5.1.6 on 2025-03-14 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='visition_date',
            new_name='visit_date',
        ),
    ]
